version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:1234@localhost:5432/postgres?schema=public"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma
    command: >
      sh -c "npx prisma generate &&
             npm run start:dev"

  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
